---
# tasks file for mariadb
- name: Install MariaDB
  ansible.builtin.apt:
    name: mariadb-server
    state: present
    update_cache: true

- name: Start and enable MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
    