---
# tasks file for prometheus
- name: Create Prometheus user
  ansible.builtin.user:
    name: prometheus
    shell: /sbin/nologin
    system: true

- name: Download Prometheus
  ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.51.2/prometheus-2.51.2.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: true

- name: Create Prometheus systemd service
  ansible.builtin.copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      ExecStart=/opt/prometheus-2.51.2.linux-amd64/prometheus \
        --config.file=/opt/prometheus-2.51.2.linux-amd64/prometheus.yml \
        --storage.tsdb.path=/opt/prometheus-2.51.2.linux-amd64/data
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd and start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    daemon_reload: true
    state: started
